name: flutter_midtrans
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0-235.0.dev

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.5.0
  midtrans_sdk: ^1.0.1
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
